language: cpp
env:
- NODE_VERSION="5.3"
os:
- linux
- osx
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq             ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew update                         ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full  ;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then brew install p7zip                  ;
  fi
- git clone https://github.com/creationix/nvm.git /tmp/.nvm; source /tmp/.nvm/nvm.sh;
  nvm install $NODE_VERSION; nvm use --delete-prefix $NODE_VERSION;
install:
- npm install
before_script:
- export TRAVIS=1
- npm install -g gulp
- gulp install
script:
- gulp build
- gulp build_plugins
