osx_image: xcode7.3

sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - icnsutils

cache:
  directories:
  - node_modules
  - $HOME/.electron

install:
  - npm install

before_script:
  - export TRAVIS=1
  - npm install

script:
  - npm run build
